/**
 * Zentrale Ablage aller sichtbaren Anzeigetexte der Anwendung.
 *
 * Backlog: "Anpassung der Anzeigetexte" - eine inhaltliche Ueberarbeitung
 * der Texte ist nicht Bestandteil des MVP. Diese zentrale Ablage soll eine
 * spaetere Anpassung erleichtern.
 */
export const uiTexts = {
  common: {
    appName: "Maschinenverwaltung",
    loading: "Wird geladen …",
    save: "Speichern",
    cancel: "Abbrechen",
    edit: "Bearbeiten",
    back: "Zurück",
    yes: "Ja",
    no: "Nein",
    confirm: "Bestätigen",
    optional: "optional",
    required: "Pflichtfeld",
    genericError:
      "Es ist ein Fehler aufgetreten. Bitte versuchen Sie es erneut.",
    unknownError:
      "Ein unerwarteter Fehler ist aufgetreten. Bitte laden Sie die Seite neu.",
    active: "Aktiv",
    inactive: "Inaktiv",
  },
  machineStatus: {
    IM_LAGER: "Im Lager",
    AUSGELIEHEN: "Ausgeliehen",
    GESPERRT: "Gesperrt",
  },
  personType: {
    MITARBEITER: "Mitarbeiter",
    SUBUNTERNEHMER: "Subunternehmer",
  },
  ownershipType: {
    EIGENTUM: "Eigentum",
    FLOTTE: "Flotte",
  },
  transactionAction: {
    CHECKOUT: "Entnahme",
    CHECKIN: "Rückgabe",
    ADMIN_CHECKIN: "Administrative Rückgabe",
    LOCK: "Gesperrt",
    UNLOCK: "Freigegeben",
  },
  transactionSource: {
    QR_APP: "QR-Anwendung",
    ADMIN: "Administration",
  },
  publicMachine: {
    unavailableTitle: "Maschine nicht verfügbar",
    unavailableText: "Diese Maschine ist aktuell nicht verfügbar.",
    notFoundTitle: "Maschine nicht gefunden",
    notFoundText:
      "Für diesen QR-Code konnte keine Maschine gefunden werden. Bitte wenden Sie sich an die zuständige Ansprechperson.",
    currentUserLabel: "Aktueller Nutzer",
    checkoutAtLabel: "Entnommen am",
    plannedReturnLabel: "Geplante Rückgabe",
    projectOrLocationLabel: "Einsatzort / Projekt",
    storageLocationLabel: "Lagerplatz",
    informationLabel: "Hinweis",
    checkoutButton: "Maschine entnehmen",
    checkinButton: "Maschine zurückgeben",
    lockedNotice: "Diese Maschine ist derzeit gesperrt.",
    checkoutSuccessTitle: "Entnahme erfolgreich",
    checkoutSuccessText: "Die Maschine wurde erfolgreich entnommen.",
    checkinSuccessTitle: "Rückgabe erfolgreich",
    checkinSuccessText: "Die Maschine wurde erfolgreich zurückgegeben.",
    formPersonLabel: "Person",
    formPersonPlaceholder: "Person auswählen …",
    formPersonSearchPlaceholder: "Name suchen …",
    formProjectOrLocationLabel: "Einsatzort oder Projekt",
    formPlannedReturnLabel: "Geplante Rückgabe",
    formCommentLabel: "Kommentar",
    submitCheckout: "Entnehmen",
    submitCheckin: "Zurückgeben",
    submitting: "Wird gespeichert …",
    noPeopleFound: "Keine Person gefunden.",
  },
  admin: {
    loginTitle: "Administration – Anmeldung",
    loginUsernameLabel: "Benutzername",
    loginPasswordLabel: "Passwort",
    loginButton: "Anmelden",
    loginError: "Benutzername oder Passwort ist falsch.",
    logoutButton: "Abmelden",
    nav: {
      machines: "Maschinen",
      people: "Personen",
      history: "Historie",
    },
    machines: {
      title: "Maschinen",
      newButton: "Neue Maschine",
      searchPlaceholder: "Suche nach Name, Hersteller, Modell, Seriennummer …",
      filterStatus: "Status",
      filterOwnership: "Eigentumstyp",
      filterActive: "Aktivstatus",
      all: "Alle",
      onlyActive: "Nur aktive",
      onlyInactive: "Nur inaktive",
      table: {
        name: "Name",
        manufacturer: "Hersteller",
        model: "Modell",
        serialNumber: "Seriennummer",
        status: "Status",
        currentUser: "Aktueller Nutzer",
        storageLocation: "Lagerplatz",
        ownership: "Eigentum",
        active: "Aktiv",
        actions: "Aktionen",
      },
      noResults: "Keine Maschinen gefunden.",
      actions: {
        open: "Öffnen",
        edit: "Bearbeiten",
        history: "Historie",
        showQr: "QR-Code",
        downloadQr: "QR-Code (PNG)",
        lock: "Sperren",
        unlock: "Freigeben",
        adminCheckin: "Administrativ zurückgeben",
        deactivate: "Deaktivieren",
        reactivate: "Reaktivieren",
      },
      confirmLock: "Soll diese Maschine gesperrt werden?",
      confirmUnlock: "Soll diese Maschine freigegeben werden?",
      confirmDeactivate:
        "Soll diese Maschine deaktiviert werden? Sie ist danach öffentlich nicht mehr buchbar.",
      confirmReactivate: "Soll diese Maschine reaktiviert werden?",
      adminCheckinTitle: "Administrative Rückgabe",
      adminCheckinReasonLabel: "Änderungsgrund",
      adminCheckinReasonPlaceholder:
        "Bitte begründen Sie die administrative Rückgabe …",
      lockInfoLabel: "Informationsfeld (öffentlich sichtbar)",
      form: {
        title: "Maschine",
        titleNew: "Neue Maschine anlegen",
        titleEdit: "Maschine bearbeiten",
        name: "Maschinenname",
        manufacturer: "Hersteller",
        modelName: "Modellname",
        serialNumber: "Seriennummer",
        storageLocation: "Lagerplatz",
        ownershipType: "Eigentumstyp",
        purchaseDateOwned: "Kaufdatum",
        purchaseDateFleet: "Übernahmedatum",
        hiltiScanCode: "Hilti-Scancode",
        alternativeCode: "Alternativcode",
        description: "Beschreibung",
        responsiblePerson: "Verantwortlicher Mitarbeiter",
        responsiblePersonNone: "Kein verantwortlicher Mitarbeiter",
        informationText: "Informationsfeld",
        qrToken: "QR-Token (automatisch erzeugt)",
        submitCreate: "Maschine anlegen",
        submitUpdate: "Änderungen speichern",
      },
    },
    people: {
      title: "Personen",
      newButton: "Neue Person",
      table: {
        displayName: "Anzeigename",
        personType: "Typ",
        company: "Firma",
        active: "Aktiv",
        actions: "Aktionen",
      },
      noResults: "Keine Personen gefunden.",
      confirmDeactivate: "Soll diese Person deaktiviert werden?",
      confirmReactivate: "Soll diese Person reaktiviert werden?",
      form: {
        titleNew: "Neue Person anlegen",
        titleEdit: "Person bearbeiten",
        displayName: "Anzeigename",
        personType: "Personentyp",
        company: "Firma",
        employeeNumber: "Personalnummer",
        phone: "Telefon",
        email: "E-Mail",
        comment: "Kommentar",
        submitCreate: "Person anlegen",
        submitUpdate: "Änderungen speichern",
      },
    },
    history: {
      title: "Historie",
      filterMachine: "Maschine",
      filterPerson: "Person",
      filterAction: "Aktion",
      filterFrom: "Von",
      filterTo: "Bis",
      table: {
        timestamp: "Zeitpunkt",
        machine: "Maschine",
        action: "Aktion",
        person: "Person",
        previousHolder: "Vorheriger Nutzer",
        plannedReturn: "Geplante Rückgabe",
        projectOrLocation: "Einsatzort / Projekt",
        comment: "Kommentar",
        source: "Quelle",
        admin: "Administrator",
      },
      noResults: "Keine Einträge gefunden.",
    },
    qr: {
      title: "QR-Code",
      downloadButton: "Als PNG herunterladen",
      targetUrlLabel: "Ziel-URL",
    },
  },
  errors: {
    machineNotFound: "Maschine wurde nicht gefunden.",
    machineInactive: "Diese Maschine ist deaktiviert.",
    machineNotInStorage: "Diese Maschine ist derzeit nicht im Lager.",
    machineNotCheckedOut: "Diese Maschine ist derzeit nicht ausgeliehen.",
    machineLocked: "Diese Maschine ist gesperrt.",
    machineAlreadyCheckedOut:
      "Diese Maschine wurde soeben bereits entnommen. Bitte laden Sie die Seite neu.",
    machineCannotLock:
      "Nur Maschinen im Lager können gesperrt werden.",
    machineCannotUnlock: "Nur gesperrte Maschinen können freigegeben werden.",
    machineCannotDeactivateCheckedOut:
      "Eine ausgeliehene Maschine kann nicht deaktiviert werden.",
    personNotFound: "Person wurde nicht gefunden.",
    personInactive: "Diese Person ist nicht aktiv.",
    personNotEmployeeOrInactive:
      "Verantwortliche Person muss ein aktiver Mitarbeiter sein.",
    validationFailed: "Bitte überprüfen Sie Ihre Eingaben.",
    plannedReturnInPast:
      "Das geplante Rückgabedatum darf nicht in der Vergangenheit liegen.",
    duplicateSerialNumber:
      "Ein Gerät mit diesem Hersteller und dieser Seriennummer existiert bereits.",
    duplicateHiltiScanCode: "Dieser Hilti-Scancode wird bereits verwendet.",
    duplicateAlternativeCode: "Dieser Alternativcode wird bereits verwendet.",
    unauthorized: "Bitte melden Sie sich an, um fortzufahren.",
    forbidden: "Sie sind nicht berechtigt, diese Aktion durchzuführen.",
  },
} as const;
